// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TinyTalk",
    platforms: [
        .iOS("18.2")
    ],
    products: [
        .iOSApplication(
            name: "TinyTalk",
            targets: ["AppModule"],
            bundleIdentifier: "com.Zikar.TinyTalk",
            teamIdentifier: "XWM9X5R5VK",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .pencil),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "We use the microphone to analyze your baby's sounds.")
            ],
            appCategory: .utilities
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Assets.xcassets"),
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
